/**
 * Style system: ClashOfCode Tournament Console — an editorial public field report with a
 * left-weighted hero, broadcast signal details, and sharp operational cards rather than a generic SaaS landing page.
 */
import PublicShell from "@/components/PublicShell";
import { ArrowUpRight, ChartNoAxesCombined, Crosshair, Eye, Gauge, Medal, RadioTower, Swords, Trophy } from "lucide-react";
import { Link } from "wouter";

const steps = [{ icon: Crosshair, count: "01", title: "Get matched", body: "Enter a focused queue or bring your own room." }, { icon: Swords, count: "02", title: "Solve head-to-head", body: "Face the same DSA problem in a live timed battle." }, { icon: Trophy, count: "03", title: "Climb the ladder", body: "Win rating, earn tiers, and prove the run." }];
const features = [{ icon: Gauge, label: "Ranked matches", text: "Smartly paced 1v1 battles designed for a fair rating climb." }, { icon: Eye, label: "Live opponent progress", text: "Track the tension, not the answer, in every match." }, { icon: ChartNoAxesCombined, label: "Leaderboards", text: "Read the season in real time—global, friends, and your bracket." }, { icon: Medal, label: "Rank tiers", text: "Progress from Bronze through Grandmaster with a clear competitive signal." }];

export default function Landing() { return <PublicShell><main><section className="landing-hero noise"><video className="hero-loop" autoPlay muted loop playsInline preload="metadata" aria-hidden="true"><source src="/manus-storage/clashofcode-hero-loop_b93b2083.mp4" type="video/mp4" /></video><div className="hero-shade" /><div className="landing-hero-content"><div className="hero-signal"><span className="live-dot" />ARENA SIGNAL / <strong>1,284 BATTLES HAPPENING NOW</strong></div><p className="hero-eyebrow">Real-time DSA competition</p><h1>Outthink.<br /><em>Outcode.</em><br />Outrank.</h1><p className="hero-copy">ClashOfCode turns data-structures and algorithms practice into <strong>real-time 1v1 coding battles</strong>. Same problem. Same clock. One player moves up.</p></div><div className="hero-numbers" aria-label="Live platform statistics"><div><span>LIVE QUEUES</span><b>21</b></div><div><span>CODE SOLVED TODAY</span><b>3,908</b></div><div><span>SEASON</span><b>03</b></div></div></section><section id="about" className="landing-section"><div className="section-intro"><p className="section-kicker">The climb / three moves</p><h2>Practice becomes a contest<br />worth returning to.</h2></div><div className="steps-grid">{steps.map(({ icon: Icon, count, title, body }) => <article key={count} className="step-card"><div className="flex items-start justify-between"><span className="step-number">{count}</span><Icon className="h-5 w-5 text-[#ff6b5a]" /></div><h3>{title}</h3><p>{body}</p><span className="step-rule" /></article>)}</div></section><section className="landing-section features-section"><div className="section-intro"><p className="section-kicker">Designed for the competitive loop</p><h2>Every signal has a purpose.</h2></div><div className="features-grid">{features.map(({ icon: Icon, label, text }, index) => <article key={label} className="feature-card"><div className="feature-index">0{index + 1}</div><Icon className="h-5 w-5 text-[#b5df73]" /><h3>{label}</h3><p>{text}</p><ArrowUpRight className="feature-arrow h-4 w-4" /></article>)}</div></section><section className="landing-cta"><div><p className="section-kicker">The arena is open</p><h2>Your next rating point<br />is already in play.</h2></div><Link href="/signup" className="primary-button"><RadioTower className="h-4 w-4" />Enter ClashOfCode</Link></section></main></PublicShell>; }
