-- 0001_init.sql
-- ClashOfCode initial database schema.
--
-- SCHEMA SOURCE OF TRUTH
--
-- Apply with:
--   pnpm migrate
--
-- IMPORTANT:
-- If this migration has already been applied to a database,
-- DO NOT edit this file. Create a new migration instead.

-- ============================================================================
-- EXTENSIONS
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;


-- ============================================================================
-- USERS
-- ============================================================================

CREATE TABLE IF NOT EXISTS users (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    username          TEXT NOT NULL,
    email             TEXT NOT NULL,

    password_hash     TEXT NOT NULL,

    rating            DOUBLE PRECISION NOT NULL DEFAULT 1500,
    rating_deviation  DOUBLE PRECISION NOT NULL DEFAULT 350,
    rating_volatility DOUBLE PRECISION NOT NULL DEFAULT 0.06,

    games_played      INTEGER NOT NULL DEFAULT 0,
    wins              INTEGER NOT NULL DEFAULT 0,
    losses            INTEGER NOT NULL DEFAULT 0,
    draws             INTEGER NOT NULL DEFAULT 0,

    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT users_rating_non_negative
        CHECK (rating >= 0),

    CONSTRAINT users_rating_deviation_positive
        CHECK (rating_deviation > 0),

    CONSTRAINT users_rating_volatility_positive
        CHECK (rating_volatility > 0),

    CONSTRAINT users_games_played_non_negative
        CHECK (games_played >= 0),

    CONSTRAINT users_wins_non_negative
        CHECK (wins >= 0),

    CONSTRAINT users_losses_non_negative
        CHECK (losses >= 0),

    CONSTRAINT users_draws_non_negative
        CHECK (draws >= 0),

    CONSTRAINT users_username_not_blank
        CHECK (length(trim(username)) >= 3),

    CONSTRAINT users_email_not_blank
        CHECK (length(trim(email)) > 0)
);

-- Case-insensitive uniqueness.
--
-- This prevents:
--   Alice
--   alice
--   ALICE
--
-- from becoming three different users.

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_username_lower
    ON users (lower(username));

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email_lower
    ON users (lower(email));

CREATE INDEX IF NOT EXISTS idx_users_rating
    ON users (rating DESC);


-- ============================================================================
-- PROBLEMS
-- ============================================================================

CREATE TABLE IF NOT EXISTS problems (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    slug            TEXT NOT NULL UNIQUE,
    title           TEXT NOT NULL,
    statement       TEXT NOT NULL,

    difficulty      TEXT NOT NULL
        CHECK (difficulty IN ('easy', 'medium', 'hard')),

    rating          INTEGER NOT NULL DEFAULT 1200,
    time_limit_ms   INTEGER NOT NULL DEFAULT 2000,
    memory_limit_kb INTEGER NOT NULL DEFAULT 262144,

    tags            TEXT[] NOT NULL DEFAULT '{}',

    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT problems_rating_positive
        CHECK (rating > 0),

    CONSTRAINT problems_time_limit_positive
        CHECK (time_limit_ms > 0),

    CONSTRAINT problems_memory_limit_positive
        CHECK (memory_limit_kb > 0),

    CONSTRAINT problems_title_not_blank
        CHECK (length(trim(title)) > 0),

    CONSTRAINT problems_statement_not_blank
        CHECK (length(trim(statement)) > 0)
);

CREATE INDEX IF NOT EXISTS idx_problems_difficulty
    ON problems (difficulty);

CREATE INDEX IF NOT EXISTS idx_problems_rating
    ON problems (rating);

-- GIN allows efficient searches through the tags array.
CREATE INDEX IF NOT EXISTS idx_problems_tags
    ON problems USING GIN (tags);


-- ============================================================================
-- TEST CASES
-- ============================================================================

-- Hidden test cases must never be returned through public problem APIs.
-- Only is_sample = true should be exposed to clients.

CREATE TABLE IF NOT EXISTS test_cases (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    problem_id      UUID NOT NULL
        REFERENCES problems(id)
        ON DELETE CASCADE,

    input           TEXT NOT NULL,
    expected_output TEXT NOT NULL,

    is_sample       BOOLEAN NOT NULL DEFAULT false,

    ordinal         INTEGER NOT NULL,

    CONSTRAINT test_cases_ordinal_non_negative
        CHECK (ordinal >= 0),

    CONSTRAINT test_cases_problem_ordinal_unique
        UNIQUE (problem_id, ordinal)
);

CREATE INDEX IF NOT EXISTS idx_test_cases_problem
    ON test_cases (problem_id, ordinal);


-- ============================================================================
-- ROOMS
-- ============================================================================

CREATE TABLE IF NOT EXISTS rooms (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    code          TEXT NOT NULL UNIQUE,

    host_user_id  UUID NOT NULL
        REFERENCES users(id)
        ON DELETE CASCADE,

    problem_id    UUID
        REFERENCES problems(id)
        ON DELETE SET NULL,

    is_private    BOOLEAN NOT NULL DEFAULT true,

    max_players   INTEGER NOT NULL DEFAULT 2,

    time_control  TEXT NOT NULL DEFAULT 'rapid',

    status        TEXT NOT NULL DEFAULT 'open'
        CHECK (
            status IN (
                'open',
                'starting',
                'in_progress',
                'closed'
            )
        ),

    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT rooms_code_not_blank
        CHECK (length(trim(code)) > 0),

    CONSTRAINT rooms_max_players_valid
        CHECK (max_players BETWEEN 2 AND 16),

    CONSTRAINT rooms_time_control_valid
        CHECK (
            time_control IN (
                'blitz',
                'rapid',
                'extended'
            )
        )
);

CREATE INDEX IF NOT EXISTS idx_rooms_status
    ON rooms (status);

CREATE INDEX IF NOT EXISTS idx_rooms_host
    ON rooms (host_user_id);

CREATE INDEX IF NOT EXISTS idx_rooms_created_at
    ON rooms (created_at DESC);


-- ============================================================================
-- ROOM MEMBERS
-- ============================================================================

CREATE TABLE IF NOT EXISTS room_members (
    room_id   UUID NOT NULL
        REFERENCES rooms(id)
        ON DELETE CASCADE,

    user_id   UUID NOT NULL
        REFERENCES users(id)
        ON DELETE CASCADE,

    ready     BOOLEAN NOT NULL DEFAULT false,

    joined_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (room_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_room_members_user
    ON room_members (user_id);

CREATE INDEX IF NOT EXISTS idx_room_members_room
    ON room_members (room_id);


-- ============================================================================
-- MATCHES
-- ============================================================================

CREATE TABLE IF NOT EXISTS matches (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    problem_id    UUID NOT NULL
        REFERENCES problems(id),

    mode          TEXT NOT NULL
        CHECK (
            mode IN (
                'ranked',
                'casual',
                'room',
                'practice'
            )
        ),

    status        TEXT NOT NULL DEFAULT 'waiting'
        CHECK (
            status IN (
                'waiting',
                'active',
                'judging',
                'completed',
                'abandoned'
            )
        ),

    player_one_id UUID NOT NULL
        REFERENCES users(id),

    player_two_id UUID
        REFERENCES users(id),

    winner_id     UUID
        REFERENCES users(id),

    room_code     TEXT
        REFERENCES rooms(code)
        ON DELETE SET NULL,

    started_at    TIMESTAMPTZ,
    ended_at      TIMESTAMPTZ,

    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT matches_players_must_differ
        CHECK (
            player_two_id IS NULL
            OR player_one_id <> player_two_id
        ),

    CONSTRAINT matches_winner_must_be_player
        CHECK (
            winner_id IS NULL
            OR winner_id = player_one_id
            OR winner_id = player_two_id
        ),

    CONSTRAINT matches_ended_after_started
        CHECK (
            ended_at IS NULL
            OR started_at IS NULL
            OR ended_at >= started_at
        ),

    CONSTRAINT matches_completed_has_end_time
        CHECK (
            status <> 'completed'
            OR ended_at IS NOT NULL
        )
);

CREATE INDEX IF NOT EXISTS idx_matches_player_one
    ON matches (player_one_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_matches_player_two
    ON matches (player_two_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_matches_status
    ON matches (status);

CREATE INDEX IF NOT EXISTS idx_matches_room_code
    ON matches (room_code);

CREATE INDEX IF NOT EXISTS idx_matches_problem
    ON matches (problem_id);

CREATE INDEX IF NOT EXISTS idx_matches_created_at
    ON matches (created_at DESC);


-- ============================================================================
-- SUBMISSIONS
-- ============================================================================

CREATE TABLE IF NOT EXISTS submissions (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    match_id      UUID
        REFERENCES matches(id)
        ON DELETE SET NULL,

    user_id       UUID NOT NULL
        REFERENCES users(id),

    problem_id    UUID NOT NULL
        REFERENCES problems(id),

    language      TEXT NOT NULL,

    source_code   TEXT NOT NULL,

    verdict       TEXT NOT NULL DEFAULT 'pending'
        CHECK (
            verdict IN (
                'pending',
                'accepted',
                'wrong_answer',
                'time_limit_exceeded',
                'memory_limit_exceeded',
                'runtime_error',
                'compilation_error',
                'internal_error'
            )
        ),

    passed_tests  INTEGER NOT NULL DEFAULT 0,

    total_tests   INTEGER NOT NULL DEFAULT 0,

    runtime_ms    INTEGER,

    memory_kb     INTEGER,

    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

    judged_at     TIMESTAMPTZ,

    CONSTRAINT submissions_passed_tests_non_negative
        CHECK (passed_tests >= 0),

    CONSTRAINT submissions_total_tests_non_negative
        CHECK (total_tests >= 0),

    CONSTRAINT submissions_passed_not_greater_than_total
        CHECK (passed_tests <= total_tests),

    CONSTRAINT submissions_runtime_non_negative
        CHECK (
            runtime_ms IS NULL
            OR runtime_ms >= 0
        ),

    CONSTRAINT submissions_memory_non_negative
        CHECK (
            memory_kb IS NULL
            OR memory_kb >= 0
        ),

    CONSTRAINT submissions_judged_time_valid
        CHECK (
            judged_at IS NULL
            OR judged_at >= created_at
        )
);

CREATE INDEX IF NOT EXISTS idx_submissions_user
    ON submissions (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_submissions_match
    ON submissions (match_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_submissions_problem
    ON submissions (problem_id);

CREATE INDEX IF NOT EXISTS idx_submissions_verdict
    ON submissions (verdict);


-- ============================================================================
-- RATINGS HISTORY
-- ============================================================================

-- One rating-history record per user per match.
--
-- This is what makes rating application idempotent:
--
--   UNIQUE(user_id, match_id)
--
-- A retry cannot apply the same match rating twice.

CREATE TABLE IF NOT EXISTS ratings_history (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    user_id       UUID NOT NULL
        REFERENCES users(id)
        ON DELETE CASCADE,

    match_id      UUID NOT NULL
        REFERENCES matches(id)
        ON DELETE CASCADE,

    rating_before DOUBLE PRECISION NOT NULL,
    rating_after  DOUBLE PRECISION NOT NULL,

    rd_before     DOUBLE PRECISION NOT NULL,
    rd_after      DOUBLE PRECISION NOT NULL,

    vol_before    DOUBLE PRECISION NOT NULL,
    vol_after     DOUBLE PRECISION NOT NULL,

    delta         DOUBLE PRECISION NOT NULL,

    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT ratings_history_rating_before_non_negative
        CHECK (rating_before >= 0),

    CONSTRAINT ratings_history_rating_after_non_negative
        CHECK (rating_after >= 0),

    CONSTRAINT ratings_history_rd_before_positive
        CHECK (rd_before > 0),

    CONSTRAINT ratings_history_rd_after_positive
        CHECK (rd_after > 0),

    CONSTRAINT ratings_history_vol_before_positive
        CHECK (vol_before > 0),

    CONSTRAINT ratings_history_vol_after_positive
        CHECK (vol_after > 0),

    UNIQUE (user_id, match_id)
);

CREATE INDEX IF NOT EXISTS idx_ratings_history_user
    ON ratings_history (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_ratings_history_match
    ON ratings_history (match_id);


-- ============================================================================
-- FRIENDSHIPS
-- ============================================================================

CREATE TABLE IF NOT EXISTS friendships (
    user_id    UUID NOT NULL
        REFERENCES users(id)
        ON DELETE CASCADE,

    friend_id  UUID NOT NULL
        REFERENCES users(id)
        ON DELETE CASCADE,

    status     TEXT NOT NULL DEFAULT 'pending'
        CHECK (
            status IN (
                'pending',
                'accepted',
                'blocked'
            )
        ),

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (user_id, friend_id),

    CONSTRAINT friendships_users_must_differ
        CHECK (user_id <> friend_id)
);

CREATE INDEX IF NOT EXISTS idx_friendships_friend
    ON friendships (friend_id);

CREATE INDEX IF NOT EXISTS idx_friendships_user_status
    ON friendships (user_id, status);

CREATE INDEX IF NOT EXISTS idx_friendships_friend_status
    ON friendships (friend_id, status);


-- ============================================================================
-- USERS UPDATED_AT TRIGGER
-- ============================================================================

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_users_updated_at ON users;

CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();