-- 0002_update_time_control_values.sql
-- Update time_control constraint to match frontend values
--
-- IMPORTANT:
-- If this migration has already been applied to a database,
-- DO NOT edit this file. Create a new migration instead.

-- Drop the old constraint
ALTER TABLE rooms DROP CONSTRAINT IF EXISTS rooms_time_control_valid;

-- Add the new constraint with the correct values
ALTER TABLE rooms
ADD CONSTRAINT rooms_time_control_valid
CHECK (
    time_control IN (
        'blitz',
        'standard',
        'deep'
    )
);

-- Update the default value from 'rapid' to 'standard'
ALTER TABLE rooms ALTER COLUMN time_control SET DEFAULT 'standard';

-- Update any existing 'rapid' values to 'standard' (migration safety)
UPDATE rooms SET time_control = 'standard' WHERE time_control = 'rapid';

-- Update any existing 'extended' values to 'deep' (migration safety)
UPDATE rooms SET time_control = 'deep' WHERE time_control = 'extended';
