-- 0003_add_user_preferences.sql
-- Add user preferences columns for settings page
--
-- IMPORTANT:
-- If this migration has already been applied to a database,
-- DO NOT edit this file. Create a new migration instead.

-- Add preferences columns to users table
ALTER TABLE users
ADD COLUMN IF NOT EXISTS rating_visible BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS activity_visible BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS quick_queue BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS reduced_motion BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS match_found_notifications BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS direct_invites BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS weekly_review BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS discoverable BOOLEAN NOT NULL DEFAULT true;

-- Add comments for clarity
COMMENT ON COLUMN users.rating_visible IS 'Show rating on public profile';
COMMENT ON COLUMN users.activity_visible IS 'Show activity/online status';
COMMENT ON COLUMN users.quick_queue IS 'Skip confirmation when entering queue';
COMMENT ON COLUMN users.reduced_motion IS 'Reduce interface animations';
COMMENT ON COLUMN users.match_found_notifications IS 'Notify when match is found';
COMMENT ON COLUMN users.direct_invites IS 'Accept direct room invitations';
COMMENT ON COLUMN users.weekly_review IS 'Send weekly summary emails';
COMMENT ON COLUMN users.discoverable IS 'Appear in player discovery';
